// data/recipes.js

const recipes = [
    {
      id: 1,
      title: "Spaghetti Carbonara",
      description: "A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.",
      ingredients: [
        "200g spaghetti",
        "100g pancetta",
        "2 large eggs",
        "50g pecorino cheese",
        "50g parmesan",
        "Freshly ground black pepper",
        "Salt",
        "2 cloves of garlic",
        "50g unsalted butter",
      ],
      steps: [
        "Put a large saucepan of water on to boil.",
        "Finely chop the pancetta, having first removed any rind.",
        "Finely grate both cheeses and mix them together.",
        "Beat the eggs in a medium bowl, season with a little freshly grated black pepper and set everything aside.",
        "Add 1 tsp salt to the boiling water, add the spaghetti and when the water comes back to the boil, cook at a constant simmer.",
        "Squash 2 peeled plump garlic cloves with the blade of a knife, just to bruise it.",
        "Melt the butter in a large frying pan and, as soon as the butter has melted, tip in the pancetta and garlic.",
        "Leave to cook on a medium heat for about 5 minutes, stirring often, until the pancetta is golden and crisp.",
        "Keep the heat under the pancetta on low. When the pasta is ready, lift it from the water with a pasta fork or tongs and put it in the frying pan with the pancetta.",
        "Mix most of the cheese in with the eggs, keeping a small handful back for sprinkling over later.",
        "Take the pan of spaghetti and pancetta off the heat.",
        "Quickly pour in the eggs and cheese. Using the tongs or a long fork, lift up the spaghetti so it mixes easily with the egg mixture, which thickens but doesn’t scramble, and everything is coated.",
        "Add extra pasta cooking water to keep it saucy.",
        "Serve immediately with a little sprinkling of the remaining cheese and a grating of black pepper.",
      ],
      image: "/images/spaghetti-carbonara.jpg",
    },
    {
      id: 2,
      title: "Chicken Curry",
      description: "A flavorful and spicy chicken curry made with a blend of spices and coconut milk.",
      ingredients: [
        "1 kg chicken, cut into pieces",
        "2 onions, finely chopped",
        "3 tomatoes, chopped",
        "4 cloves of garlic, minced",
        "1 inch ginger, minced",
        "2 green chilies, slit",
        "1 tsp turmeric powder",
        "1 tsp red chili powder",
        "2 tsp coriander powder",
        "1 tsp cumin powder",
        "1 tsp garam masala",
        "400 ml coconut milk",
        "2 tbsp oil",
        "Salt to taste",
        "Fresh coriander leaves for garnish",
      ],
      steps: [
        "Heat oil in a large pan over medium heat.",
        "Add the onions and sauté until golden brown.",
        "Add the garlic, ginger, and green chilies and sauté for another minute.",
        "Add the tomatoes and cook until they are soft and mushy.",
        "Add the turmeric, red chili powder, coriander powder, and cumin powder and cook for a few minutes until the spices are fragrant.",
        "Add the chicken pieces and cook until they are browned on all sides.",
        "Add the coconut milk and salt, and bring to a boil.",
        "Reduce the heat and let it simmer for 20-25 minutes, or until the chicken is cooked through.",
        "Stir in the garam masala and cook for another 2 minutes.",
        "Garnish with fresh coriander leaves and serve hot with rice or naan.",
      ],
      image: "/images/chicken-curry.jpg",
    },
    // Add more recipes as needed
  ];
  
  export default recipes;